### ISSUE TITLE
Upgrade angular version to latest

### ISSUE THREAD

**Issue by bugthesystem** [ziyasal/rdash-angular2#2]

**Comment by lmessinger** [comment]
Hi, 

Any idea why I got the below list of errors , on npm run serve.dev ?

thanks very much
Lior

app/app.ts(1,58): error TS2307: Cannot find module 'angular2/angular2'.
app/app.ts(2,63): error TS2307: Cannot find module 'angular2/router'.
app/components/alerts/alerts.ts(1,47): error TS2307: Cannot find module 'angular2/angular2'.
app/components/dashboard/dashboard.ts(1,31): error TS2307: Cannot find module 'angular2/angular2'.
app/components/dashboard/dashboard.ts(3,22): error TS2307: Cannot find module 'components/alerts/alerts'.
app/components/dashboard/dashboard.ts(6,25): error TS2307: Cannot find module 'components/rd-loading/rd-loading'.
app/components/dashboard/dashboard.ts(7,24): error TS2307: Cannot find module 'components/rd-widget/rd-widget'.
app/components/dashboard/dashboard.ts(9,30): error TS2307: Cannot find module 'components/rd-widget-header/rd-widget-header'.
app/components/dashboard/dashboard.ts(10,28): error TS2307: Cannot find module 'components/rd-widget-body/rd-widget-body'.
app/components/dashboard/dashboard.ts(11,30): error TS2307: Cannot find module 'components/rd-widget-footer/rd-widget-footer'.
app/components/dashboard/dashboard.ts(13,30): error TS2307: Cannot find module 'components/server-list-view/server-list-view'.
app/components/dashboard/dashboard.ts(14,33): error TS2307: Cannot find module 'services/server_list'.
app/components/dashboard/dashboard.ts(16,28): error TS2307: Cannot find module '
....

**Comment by Halpha** [comment]
I have the same issues and I see then no theme. Looks like the css is missing on the site. I will try to take a look into the code as well..

**Comment by efi-mk** [comment]
@lmessinger / @Halpha  did you manage solving your problem ?

**Comment by bugthesystem** [comment]
hi @all I have started to upgrade angular to latest version in **angular-upgrade** branch

**Comment by bugthesystem** [comment]
Hi @all,I have upgraded angular to latest version so this should be fixed [this](92b350b34c9325a65003dcd3411a9ac7986d117d)
